### ISSUE TITLE
"Plan" doesn't handle projects which have no phases

### ISSUE THREAD

**Issue by turt2live** [vector-im/feature-dashboard#34]
it just renders a blank page. It should show all issues under "Unphased" instead.

**Comment by jryans** [comment]
Just to double check I am seeing the same as you, what URL were you trying?

**Comment by jryans** [comment]
Should maybe be fixed by https://github.com/vector-im/feature-dashboard/commit/543d1d95891e24f3dfb40c0d7d7b6bb9879bf02f, but let me know if you still see an issue for your URL.

**Comment by turt2live** [comment]
It was https://vector-im.github.io/feature-dashboard/#/plan?label=feature%3Asoftlogout&repo=vector-im%2Friot-web&repo=vector-im%2FriotX-android&repo=vector-im%2Friot-ios and it looks like that issue did indeed solve it. Thanks!
