### ISSUE TITLE
Simplify summary view

### ISSUE THREAD

**Issue by jryans** [vector-im/feature-dashboard#50]
There are too many columns on the summary view at the moment, so it's hard to make judgements about it. Instead, we could change to presenting:

* everything that matches the search query and doesn't have the label `suggestion` or `bug` as "planned work"
* everything that matches the search query and doesn't have the label `suggestion` but does have the label `bug` as "bug"

**Comment by jryans** [comment]
I believe an implied result of this simplification would be that the `feature` label for marking "planned work" wouldn't be needed any more, under the assumption that it should be the default "type" of issue and then it's one less label to think about.

@manuroe, as you are the main user of the summary view today, any opinions on this idea?

**Comment by manuroe** [comment]
I cannot see any other types of issue than feature and bug.
I would be happy to remove this `feature` label. The summary view will be lighter (no more OTHER columns) and this will remove one case of bugs in your labels.

**Comment by jryans** [comment]
This is now live.
