### ISSUE TITLE
Add a bug button to the plan view

### ISSUE THREAD

**Issue by manuroe** [vector-im/feature-dashboard#63]
It will prefill the new issue with the `bug` label. Thus, bug issues will go to the right column into the summary view.
Please also add the link for the user story to new isssue :)

**Comment by jryans** [comment]
> Please also add the link for the user story to new isssue :)

I'll handle this separately in https://github.com/vector-im/feature-dashboard/issues/62.

**Comment by jryans** [comment]
This is now live.
