### ISSUE TITLE
Show key labels like blocked, needs-X on plan view

### ISSUE THREAD

**Issue by jryans** [vector-im/feature-dashboard#73]
This will help to highlight which issue are stuck for some reason.

**Comment by turt2live** [comment]
@jryans I assume this is meant for the feature dashboard? (have moved)

**Comment by jryans** [comment]
Haha, oh yeah, thanks, not sure how I did that... 😰

**Comment by jryans** [comment]
Fixed by https://github.com/vector-im/feature-dashboard/pull/75
