### ISSUE TITLE
Add the ability to message yourself

### ISSUE THREAD

**Issue by billsiniam** [vector-im/feature-dashboard#76]
All devices have the ability to SHARE to other platforms. Often its necessary when not on your main device to SEND (share) yourself a message or image. Riot does not allow you to send (share) a message to YOURSELF.
The opportunity to write yourself is also VERY handy to take notes so that you don't need to LEAVE the riot platform to take notes.

**Comment by t3chguy** [comment]
That is entirely unrelated to the Feature Dashboard project.

> A task summary, plan, and burndown chart for building software together
